const answers = [
    "It is Certain",
    "Outlook is good",
    "You may rely on it",
    "Ask again later",
    "Concentrate and ask again",
    "Reply hazy, try again",
    "No",
    "My sources say no",
    "Yes",
    "What is that you’re wearing!? Oh wait, did you ask a question. Sorry distracted by that hideo- um, unique choice ya got there.... ok, ask again",
    "Oh? You wanted me to answer that...as in it was a real question... whoops, sorry",
    "Yes yes, the outcome looks good. All positive vibes & such. Now, can I finish watching my show",
    "Sooooo, let me get this straight....out of anything you could ask me, you asked that? Ok... mmmm...oh dear! Yeah, not what you wanted. Sorry",
    "Word of advice, check your milk date before you drink it... actually never mind, that was pretty funny to watch... :laughing: Oh & yeah yeah, sure to your question",
    "Reply hazy... cause I’m not awake yet. Ask again later",
    "I said ask later, this isn’t later...",
    "Ok, not bad! Out look is pretty good",
    "Oh yeah, hope you weren’t banking on me saying something positive",
    "Yes, go for it! But don’t blame me if it goes bad",
    "Yes Yes....now, ask me the real question you have sitting there in your mind",
    "*tap tap* Is this thing on? No, not a mic....your brain! Hellllooo Mcfly, switch on",
    "Well lets see....it could be good, it could be bad. Which do you think it will be",
    "Not in this life time",
    "Here is a quarter, call someone who half cares",
    "Seek the answer within... And leave me alone",
    "I encourage you to go for it",
    "Don't know, blame it on the rain",
    "This question... *again*, really",
    "Why don’t you do us all a favor...put the phone down (or better yet the controller) & go to sleep",
    "I’m in a good mood, and yes the outcome looks good for you! No sarcasm....this time",
    "Why don't you ask the last idiot who asked a question to ask this one for you",
    "Reply hazy... wait... It is clearing... OWWW my eyes, thanks",
    "Hahahahahaha you really want me to answer that",
    "Yes, yes, 1000 times yes",
    "You told me to F off before, why should I answer you",
    "Deep breath, concentrate and ask agai... actually the answer will still be no",
    "And the answer is YES! Quick, ask me another one before this wears off",
    "Hahahhaa sorry, I just saw you trying that. All I have to say is please record it",
    "Outlook says no.... Hey, don’t get mad at me, you asked the question",
    "Outlook is good, if you know where to look, how far to look, and if you look enough",
    "Quit asking such mean things...You wouldn’t like it if your friends picked on you like that. Oh wait, never mind....they do",
    "Yes,  I did answer the question, you just weren’t paying attention & no I’m not repeating myself",
    "Sleep, what is this sleep everyone speaks of? I wanna try it"
];

module.exports = answers;